ARG BASE_IMAGE=rocm/pytorch:rocm7.0.2_ubuntu24.04_py3.12_pytorch_release_2.8.0
ARG BNB_REPO="https://github.com/ROCm/bitsandbytes"
ARG BNB_BRANCH="4fa939b"

FROM ${BASE_IMAGE} AS base

ARG PYTORCH_ROCM_ARCH=gfx1101;gfx1100;gfx1200;gfx1201
ENV PYTORCH_ROCM_ARCH=${PYTORCH_ROCM_ARCH}

ARG PYTHON_VERSION=3.12

RUN mkdir -p /app
WORKDIR /app
ENV DEBIAN_FRONTEND=noninteractive

RUN pip install -U packaging 'cmake<4' ninja wheel 'setuptools<80' pybind11 Cython

FROM base AS build_amdsmi
RUN cd /opt/rocm/share/amd_smi \
    && pip wheel . --wheel-dir=dist
RUN mkdir -p /app/install && cp /opt/rocm/share/amd_smi/dist/*.whl /app/install

FROM base AS build_bitsandbytes
ARG BNB_REPO
ARG BNB_BRANCH
RUN git clone ${BNB_REPO} bitsandbytes
RUN cd bitsandbytes \
    && git checkout ${BNB_BRANCH} \
    && git submodule update --init
RUN cd bitsandbytes \
    && cmake -DCOMPUTE_BACKEND=hip -DBNB_ROCM_ARCH=${PYTORCH_ROCM_ARCH} -S . \
    && make
RUN cd bitsandbytes \
    && python3 setup.py bdist_wheel --dist-dir=dist
RUN mkdir -p /app/install && cp /app/bitsandbytes/dist/*.whl /app/install

FROM base AS final
RUN mkdir -p /install-dependencies
RUN --mount=type=bind,from=build_amdsmi,src=/app/install/,target=/install \
    cp /install/*.whl /install-dependencies
RUN --mount=type=bind,from=build_bitsandbytes,src=/app/install/,target=/install \
    cp /install/*.whl /install-dependencies

ARG BASE_IMAGE
ARG BNB_REPO
ARG BNB_BRANCH
RUN echo "BASE_IMAGE: ${BASE_IMAGE}" > /app/versions.txt \
    && echo "BNB_REPO: ${BNB_REPO}" >> /app/versions.txt \
    && echo "BNB_BRANCH: ${BNB_BRANCH}" >> /app/versions.txt
